// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEwvQoiU78YQ9wZqVOZFN5Otp5DYXojJ8',
    appId: '1:255386099897:web:af933042fc91ac3f4efb68',
    messagingSenderId: '255386099897',
    projectId: 'crud-ujaiahmad',
    authDomain: 'crud-ujaiahmad.firebaseapp.com',
    storageBucket: 'crud-ujaiahmad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdM1QRozm2VlQ3BAXNZrykmveh2VdGkN0',
    appId: '1:255386099897:android:6312ff9714644b784efb68',
    messagingSenderId: '255386099897',
    projectId: 'crud-ujaiahmad',
    storageBucket: 'crud-ujaiahmad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM1Zi1c4F6yff0fOkL9aMvy2C0xFxUVQQ',
    appId: '1:255386099897:ios:a18226038b067df34efb68',
    messagingSenderId: '255386099897',
    projectId: 'crud-ujaiahmad',
    storageBucket: 'crud-ujaiahmad.appspot.com',
    iosBundleId: 'com.example.crudProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM1Zi1c4F6yff0fOkL9aMvy2C0xFxUVQQ',
    appId: '1:255386099897:ios:a18226038b067df34efb68',
    messagingSenderId: '255386099897',
    projectId: 'crud-ujaiahmad',
    storageBucket: 'crud-ujaiahmad.appspot.com',
    iosBundleId: 'com.example.crudProject',
  );
}
